$(function() {
  $('input.autocomplete').autocomplete({
    data: {
"0ad ": null,
"3dxmas-demo ": null,
"2048 - puzzle game ": null,
"abiword ": null,
"adapta theme ": null,
"adguard home ": null,
"adobe acrobat reader ": null,
"flash player ": null,
"airshark ": null,
"airtame ": null,
"aisleriot ": null,
"akonadi ": null,
"akregator ": null,
"alacarte ": null,
"alacritty ": null,
"ampare ": null,
"amsynth ": null,
"amule ": null,
"anbox ": null,
"android ": null,
"anydesk ": null,
"apache ": null,
"apper ": null,
"appstream ": null,
"arc theme ": null,
"arduino ": null,
"aria2c ": null,
"ario ": null,
"ark ": null,
"artikulate ": null,
"assistant ": null,
"astromenace ": null,
"atani ": null,
"atari ": null,
"atomix ": null,
"atom ": null,
"atril ": null,
"audacious ": null,
"audacity ": null,
"audex ": null,
"audiocd-kio ": null,
"autenticador ": null,
"authpass ": null,
"autopilot-qt ": null,
"autoskola3d ": null,
"autoskola-free6 ": null,
"avahi ": null,
"axel ": null,
"baobab ": null,
"basket ": null,
"battle tanks ": null,
"beaver ": null,
"biblereader ": null,
"bibletime ": null,
"bitcoin ": null,
"bittorrent ": null,
"blanket ": null,
"blender ": null,
"blink ": null,
"blobwars ": null,
"blockout ": null,
"blueberry ": null,
"bluedevil ": null,
"bluefish ": null,
"blueman ": null,
"bluez ": null,
"boinc ": null,
"bolls ": null,
"bomber ": null,
"bombsquad ": null,
"bootstack-elasticsearch ": null,
"botfather ": null,
"bottle ": null,
"bovo ": null,
"bower ": null,
"boxtron ": null,
"brackets ": null,
"brasero ": null,
"brave ": null,
"breeze ": null,
"cairo-dock ": null,
"caja ": null,
"calf ": null,
"calibre ": null,
"calligra ": null,
"cantarell-fonts ": null,
"celestia ": null,
"celluloid ": null,
"certbot ": null,
"chart ": null,
"cheese ": null,
"chessx ": null,
"choqok ": null,
"chromeos ": null,
"chromium ": null,
"chromium-bsu ": null,
"cinnamon ": null,
"cipher ": null,
"clamtk ": null,
"claws-mail ": null,
"clipaste ": null,
"clipgrab ": null,
"cobang ": null,
"cockpit ": null,
"codeblocks ": null,
"codebreakers ": null,
"code ": null,
"code - oss ": null,
"colibri ": null,
"conky-manager ": null,
"converseen ": null,
"coolreader ": null,
"cpufreq ": null,
"cpustat ": null,
"cups ": null,
"darkchat ": null,
"darktable ": null,
"dav1d ": null,
"dbeaver ": null,
"dconf-editor ": null,
"deadbeef ": null,
"deepin gtk+ theme ": null,
"deepin gtk+ theme (dark) ": null,
"deepin-boot-maker ": null,
"deepin-calculator ": null,
"deepin-calendar ": null,
"deepin-compressor ": null,
"deepin-control-center ": null,
"deepin-draw ": null,
"deepin-editor ": null,
"deepin-file-manager ": null,
"deepin-image-viewer ": null,
"deepin-movie ": null,
"deepin-music ": null,
"deepin-picker ": null,
"deepin-screenshot ": null,
"deepin-screen-recorder ": null,
"deepin-system-monitor ": null,
"deepin-terminal ": null,
"deepin-voice-note ": null,
"deepin-voice-recorder ": null,
"deerportal ": null,
"deezer player ": null,
"deja-dup ": null,
"deluge ": null,
"desmume ": null,
"devede ": null,
"dia ": null,
"diffpdf ": null,
"digikam ": null,
"dillo ": null,
"directpdf ": null,
"discographer ": null,
"discord ": null,
"discover ": null,
"djview ": null,
"dlna ": null,
"dmidecode-tool ": null,
"dnslookup ": null,
"dnsmasq ": null,
"docker ": null,
"dolphin emulator ": null,
"dolphin ": null,
"dolphin-emu ": null,
"dosbox ": null,
"download accelerator ": null,
"drawio ": null,
"dvdstyler ": null,
"easyssh ": null,
"easytag ": null,
"efl ": null,
"electronplayer ": null,
"electrum ": null,
"emacs ": null,
"engrampa ": null,
"eog ": null,
"etoys ": null,
"ettercap-gtk ": null,
"evernote ": null,
"evince ": null,
"evolution ": null,
"extreme tuxracer ": null,
"ezquake ": null,
"facebook ": null,
"fakecam ": null,
"falkon ": null,
"fast ": null,
"fbreader ": null,
"fceux ": null,
"fcitx ": null,
"feathernotes ": null,
"featherpad ": null,
"feedreader ": null,
"ffmpeg ": null,
"fightcade ": null,
"figlet ": null,
"figma ": null,
"filebot ": null,
"filelight ": null,
"filezilla ": null,
"file-roller ": null,
"filmographer ": null,
"finance ": null,
"firefox ": null,
"firefox-i18n-pt": null,
"firefox-i18n-es": null,
"firetools ": null,
"firewall ": null,
"firmware ": null,
"fish ": null,
"flameshot ": null,
"flappy ": null,
"flare ": null,
"flashprint ": null,
"flatbuffers ": null,
"flatseal ": null,
"flat-remix-gtk ": null,
"flightgear ": null,
"flow ": null,
"fluid ": null,
"flutter ": null,
"foliate ": null,
"fondo ": null,
"fontfinder ": null,
"fontforge ": null,
"fontmatrix ": null,
"fontvuer ": null,
"font manager ": null,
"foobar2000 ": null,
"foobillard-plus ": null,
"fortune ": null,
"fosstriangulator ": null,
"fotos ": null,
"fototoon ": null,
"fourier ": null,
"foxdot ": null,
"fractal ": null,
"mpv ": null,
"vokoscreen ": null,
"lutris ": null,
"fractionbounce ": null,
"fragments ": null,
"franz ": null,
"freecad ": null,
"freecell ": null,
"freeciv ": null,
"freecol ": null,
"freedoom: ": null,
"freedroidrpg ": null,
"freefilesync ": null,
"freemind ": null,
"freeorion ": null,
"freeoffice ": null,
"softmaker office ": null,
"freeplane ": null,
"freetube ": null,
"lazarus ": null,
"frescobaldi ": null,
"frets on fire ": null,
"frozen bubble ": null,
"fswebcam ": null,
"fs-tools ": null,
"fwbuilder ": null,
"fwloader ": null,
"fwupd ": null,
"gajim ": null,
"gala ": null,
"galleon ": null,
"gambas3 ": null,
"gamemode ": null,
"game-2048 ": null,
"gaui-counter ": null,
"gaupol ": null,
"gbrainy ": null,
"gcolor ": null,
"gcompris ": null,
"gdu-disk-usage-analyzer ": null,
"geany ": null,
"geary ": null,
"gedit ": null,
"geeqie ": null,
"geewallet ": null,
"gemini ": null,
"genius ": null,
"genpw ": null,
"geocoder ": null,
"geogebra ": null,
"ghostcloud ": null,
"ghostwriter ": null,
"gimagereader ": null,
"gimp ": null,
"gisto ": null,
"gitea ": null,
"giter ": null,
"gitg ": null,
"github ": null,
"gitignore ": null,
"gitkraken ": null,
"gitter ": null,
"git-cola ": null,
"git-repo ": null,
"git-tidy ": null,
"gkraken ": null,
"glabels ": null,
"glade ": null,
"gladupe ": null,
"glances ": null,
"glate ": null,
"glide ": null,
"glimpse ": null,
"gmailfilter ": null,
"gmail desktop ": null,
"gmusicbrowser ": null,
"gmusic ": null,
"gm synth ": null,
"gnac ": null,
"gnocchi ": null,
"gnokii ": null,
"gnome 2048 ": null,
"gnome boxes ": null,
"gnome calculator ": null,
"gnome calendar ": null,
"gnome characters ": null,
"gnome chess ": null,
"gnome clocks ": null,
"gnome contacts ": null,
"gnome dictionary ": null,
"gnome font viewer ": null,
"gnome hitori ": null,
"gnome klotski ": null,
"gnome logs ": null,
"gnome mahjongg ": null,
"gnome mapas ": null,
"gnome mines ": null,
"gnome nibbles ": null,
"gnome reversi ": null,
"gnome robots ": null,
"gnome sudoku ": null,
"gnome system monitor ": null,
"gnome taquin ": null,
"gnome tela via rede ": null,
"gnome tetravex ": null,
"gnome twitch ": null,
"gnome web ": null,
"gnome xadrez ": null,
"gnome-3-38-2004 ": null,
"gnome-3-38-2004-sdk ": null,
"gnome-2048 ": null,
"gnome-books ": null,
"gnome-boxes ": null,
"gnome-break-timer ": null,
"gnome-builder ": null,
"gnome-calculator ": null,
"gnome-calendar ": null,
"gnome-characters ": null,
"gnome-chess ": null,
"gnome-clocks ": null,
"gnome-color-manager ": null,
"gnome-contacts ": null,
"gnome-control-center ": null,
"gnome-dictionary ": null,
"gnome-disk-utility ": null,
"gnome-documents ": null,
"gnome-easytag ": null,
"gnome-firmware ": null,
"gnome-font-viewer ": null,
"gnome-games ": null,
"gnome-hitori ": null,
"gnome-klotski ": null,
"gnome-latex ": null,
"gnome-logs ": null,
"gnome-mahjongg ": null,
"gnome-maps ": null,
"gnome-mines ": null,
"gnome-mplayer ": null,
"gnome-multi-writer ": null,
"gnome-music ": null,
"gnome-nibbles ": null,
"gnome-notes ": null,
"gnome-packagekit ": null,
"gnome-passwordsafe ": null,
"gnome-phone-manager ": null,
"gnome-photos ": null,
"gnome-pie ": null,
"gnome-podcasts ": null,
"gnome-power-manager ": null,
"gnome-recipes ": null,
"gnome-robots ": null,
"gnome-screenshot ": null,
"gnome-search-tool ": null,
"gnome-shell ": null,
"gnome-software ": null,
"gnome-sound-recorder ": null,
"gnome-subtitles ": null,
"gnome-sudoku ": null,
"gnome-system-log ": null,
"gnome-system-monitor ": null,
"gnome-taquin ": null,
"gnome-terminal ": null,
"gnome-tetravex ": null,
"gnome-todo ": null,
"gnome-tweaks ": null,
"gnome-usage ": null,
"gnome-weather ": null,
"gnomit ": null,
"gnote ": null,
"gnucash ": null,
"gnuchess ": null,
"gnumeric ": null,
"gnuradio ": null,
"gochat ": null,
"goobox ": null,
"goodvibes ": null,
"good job ": null,
"google cloud ": null,
"google chrome ": null,
"google docs ": null,
"google photos ": null,
"google play ": null,
"govc-axw ": null,
"go-live ": null,
"go-myip ": null,
"go-swagger ": null,
"go-yt ": null,
"gpac ": null,
"gparted ": null,
"gpassmanager ": null,
"gpaste ": null,
"gphoto ": null,
"gpicview ": null,
"gping ": null,
"gpodder ": null,
"gpredict ": null,
"gprename ": null,
"gpsbabel ": null,
"gpscorrelate ": null,
"gpsprune ": null,
"gps ": null,
"gravit designer ": null,
"grub-customizer ": null,
"gscan2pdf ": null,
"gsequencer ": null,
"gsmartcontrol ": null,
"gtranslator ": null,
"guake ": null,
"gufw ": null,
"guitarix ": null,
"gummi ": null,
"guvcview ": null,
"gyre ": null,
"g'mic ": null,
"haguichi ": null,
"handbrake ": null,
"hanoi ": null,
"hardinfo ": null,
"hatari ": null,
"headset ": null,
"health ": null,
"heaptrack ": null,
"hearts ": null,
"hedgewars ": null,
"heimdall ": null,
"helm ": null,
"heroku ": null,
"higan ": null,
"htop ": null,
"icedtea ": null,
"icq ": null,
"info center ": null,
"inkscape ": null,
"instagraph ": null,
"instagram ": null,
"instalador de fontes ": null,
"irpf ": null,
"java jre": null,
"java jre openjdk": null,
"java jre oracle": null,
"java sdk": null,
"jdownloader ": null,
"jedit ": null,
"jenkins ": null,
"jpdf tweak ": null,
"jq ": null,
"jstest-gtk ": null,
"juju ": null,
"juk ": null,
"julius ": null,
"k3b ": null,
"kaccounts-providers ": null,
"kaddressbook ": null,
"kaffeine ": null,
"kafkactl ": null,
"kaidan ": null,
"kajongg ": null,
"kakoune code editor ": null,
"kalarm ": null,
"kalenderwoche ": null,
"kale ": null,
"kalgebra ": null,
"kalzium ": null,
"kamera ": null,
"kamoso ": null,
"kanagame ": null,
"kanagram ": null,
"kapman ": null,
"kate ": null,
"katomic ": null,
"kbibtex ": null,
"kblackbox ": null,
"kblocks ": null,
"kbounce ": null,
"kbreakout ": null,
"kbruch ": null,
"kb-manager ": null,
"kcachegrind ": null,
"kcalc ": null,
"kcharselect ": null,
"kchess ": null,
"kchmviewer ": null,
"kcm-fcitx ": null,
"kcm-wacomtablet ": null,
"kcolorchooser ": null,
"kcron ": null,
"kdeconnect ": null,
"kdegraphics-mobipocket ": null,
"kdegraphics-thumbnailers ": null,
"kdenetwork-filesharing ": null,
"kdenlive ": null,
"kdeplasma-addons ": null,
"kdesvn ": null,
"kdevelop ": null,
"kdialog ": null,
"kdiamond ": null,
"kdictionary ": null,
"kdiff3 ": null,
"kdiskmark ": null,
"keepapp ": null,
"keepass ": null,
"kexi ": null,
"keyhole ": null,
"keyrunner ": null,
"keysign ": null,
"kfind ": null,
"kfit ": null,
"kfloppy ": null,
"kfourinline ": null,
"kgeography ": null,
"kget ": null,
"kgoldrunner ": null,
"kgpg ": null,
"kgraphviewer ": null,
"khangman ": null,
"khelpcenter ": null,
"khronos ": null,
"kicad ": null,
"kid3 ": null,
"kimagemapeditor ": null,
"kindle comic converter ": null,
"kinfocenter ": null,
"kiosc ": null,
"kio-gdrive ": null,
"kipi-plugins ": null,
"kjots ": null,
"kjumpingcube ": null,
"klavaro ": null,
"klayout ": null,
"kleopatra ": null,
"klettres ": null,
"klickety ": null,
"klines ": null,
"kloudconference ": null,
"kloudtalk ": null,
"klystrack ": null,
"kmag ": null,
"kmahjongg ": null,
"kmail ": null,
"kmines ": null,
"kmix ": null,
"kmousetool ": null,
"kmouth ": null,
"kmplayer ": null,
"kmplot ": null,
"kms-serverproxy-demo ": null,
"kmymoney ": null,
"knavalbattle ": null,
"knctl ": null,
"knetwalk ": null,
"knights ": null,
"knotes ": null,
"knowte ": null,
"kobodeluxe ": null,
"kobo deluxe ": null,
"koch-morse tutor ": null,
"kodi ": null,
"kolf ": null,
"kolibri ": null,
"kollision ": null,
"kolourpaint ": null,
"kompare ": null,
"kompozer ": null,
"kongress ": null,
"kong ": null,
"konquest ": null,
"konsole ": null,
"konstructs ": null,
"kontact ": null,
"kontrast ": null,
"konversation ": null,
"koombo ": null,
"kopete ": null,
"kopiaui ": null,
"kops ": null,
"korganizer ": null,
"kotatogram ": null,
"kotlin ": null,
"kpatience ": null,
"kphotoalbum ": null,
"krdc ": null,
"krename ": null,
"kreversi ": null,
"kreya ": null,
"krfb ": null,
"krita ": null,
"kronometer ": null,
"krop ": null,
"kruler ": null,
"krusader ": null,
"kshisen ": null,
"kshutdown ": null,
"ksirk ": null,
"ksnakeduel ": null,
"ksnip ": null,
"kspaceduel ": null,
"ksquares ": null,
"kstars ": null,
"ksudoku ": null,
"ksysguard ": null,
"ksystemlog ": null,
"kteatime ": null,
"ktimer ": null,
"ktimetracker ": null,
"ktorrent ": null,
"ktouch ": null,
"ktuberling ": null,
"ktube ": null,
"kturtle ": null,
"kubernetes ": null,
"kube ": null,
"kvantum-qt5 ": null,
"kvirc ": null,
"kwalletmanager ": null,
"kwave ": null,
"kwordquiz ": null,
"kwrite ": null,
"k-sudoku ": null,
"languagetool ": null,
"latte-dock ": null,
"lazarus ": null,
"lbreakout2 ": null,
"leafpad ": null,
"lens ": null,
"librecad ": null,
"libreoffice ": null,
"libreoffice-still ": null,
"libreoffice-fresh ": null,
"libreoffice pt br ": null,
"tycoon ": null,
"livetuner ": null,
"livewallpaper ": null,
"llvm ": null,
"mahjong ": null,
"mailspring ": null,
"mame ": null,
"maps ": null,
"mapton ": null,
"marble ": null,
"meme ": null,
"memorize ": null,
"mgba ": null,
"microsoft azure storage explorer ": null,
"microsoft teams ": null,
"midori ": null,
"minecraft ": null,
"minesweeper ": null,
"minetest ": null,
"mingw-w64 ": null,
"minidlna ": null,
"minigalaxy ": null,
"minitube ": null,
"mixxx ": null,
"mkvtoolnix-gui ": null,
"mongo ": null,
"mono ": null,
"moonlight ": null,
"moonplayer ": null,
"mousepad ": null,
"mp3gain ": null,
"mp3splt-gtk ": null,
"mtpaint ": null,
"mynews ": null,
"mypaint ": null,
"mysql ": null,
"natron ": null,
"nautilus ": null,
"midori ": null,
"nebula ": null,
"nemo ": null,
"neochat ": null,
"neovim ": null,
"nestopia ": null,
"netbeans ": null,
"netron ": null,
"netsurf ": null,
"network-manager ": null,
"nextcloud ": null,
"nmap ": null,
"nm-connection-editor ": null,
"node.js ": null,
"nootka ": null,
"notes ": null,
"numix ": null,
"nvidia-settings ": null,
"nxcloud ": null,
"nymea:app ": null,
"obconf ": null,
"obsidian ": null,
"obs studio ": null,
"ocrfeeder ": null,
"onboard ": null,
"onefetch ": null,
"onenote ": null,
"onionshare ": null,
"onlyoffice ": null,
"openarena ": null,
"openboard ": null,
"opencomic ": null,
"openh264 ": null,
"openjdk jre ": null,
"openjdk sdk ": null,
"openmsx ": null,
"openmvg ": null,
"openmvs ": null,
"openscad ": null,
"openshot ": null,
"opentoonz ": null,
"open babel ": null,
"open drive ": null,
"opera browser ": null,
"oracle-cloud-agent ": null,
"orchis theme ": null,
"organizer ": null,
"aisleriot ": null,
"pageedit ": null,
"paint ": null,
"pantheon-calculator ": null,
"pantheon-calendar ": null,
"pantheon-code ": null,
"pantheon-files ": null,
"pantheon-music ": null,
"pantheon-screenshot ": null,
"pantheon-shortcut-overlay ": null,
"pantheon-terminal ": null,
"paprefs ": null,
"parcellite ": null,
"parlatype ": null,
"parley ": null,
"parole ": null,
"parsec ": null,
"partitionmanager ": null,
"passvault ": null,
"pavucontrol ": null,
"pcmanfm ": null,
"pcsx2 ": null,
"pdfarranger ": null,
"pdfedit ": null,
"pdfmerger ": null,
"pdf arranger ": null,
"peazip ": null,
"peco ": null,
"peek ": null,
"pegasus ": null,
"photoflare ": null,
"photogimp ": null,
"photoscape ": null,
"phototonic ": null,
"phpstorm ": null,
"php ": null,
"picodrive ": null,
"picom ": null,
"pictool ": null,
"picviewer ": null,
"pidgin ": null,
"pingus ": null,
"pinta ": null,
"pitivi ": null,
"pje office ": null,
"shodo ": null,
"plasma5-applets-active-window-control ": null,
"plasma5-applets-thermal-monitor ": null,
"plasma5-applets-weather-widget ": null,
"plasma-desktop ": null,
"plasma-disks ": null,
"plasma-nm ": null,
"plasma-pa ": null,
"plasma-sdk ": null,
"plasma-vault ": null,
"playonlinux ": null,
"plex media server ": null,
"pluma ": null,
"podcast ": null,
"poedit ": null,
"polar ": null,
"pomatez ": null,
"pomotroid ": null,
"popsicle ": null,
"pop gtk theme ": null,
"pop-themes ": null,
"poweriso ": null,
"powershell ": null,
"print-manager ": null,
"projectlibre ": null,
"proji ": null,
"prometheus ": null,
"promreg ": null,
"propelleride ": null,
"prospect mail ": null,
"protogrid ": null,
"protonmail ": null,
"protontricks ": null,
"proton ": null,
"pulseaudio volume control ": null,
"pulseaudio-equalizer-ladspa ": null,
"pulseeffects ": null,
"pulsemixer ": null,
"pulseview ": null,
"puzzles ": null,
"pychess ": null,
"qalculate ": null,
"qarma ": null,
"qastools ": null,
"qbalance ": null,
"qbittorrent ": null,
"qcachegrind ": null,
"qcad ": null,
"qcheckers ": null,
"qcomicbook ": null,
"qctools ": null,
"qemu ": null,
"qemu-virgil ": null,
"qgit ": null,
"qmmp ": null,
"qogir ": null,
"qopenvpn ": null,
"qortal ui ": null,
"qpdfview ": null,
"qqmusic ": null,
"qr code generator ": null,
"qshodan ": null,
"qsnapstore ": null,
"qspectrumanalyzer ": null,
"qstamina ": null,
"qstardict ": null,
"qstopmotion ": null,
"qsynth ": null,
"qtcreator ": null,
"qtencodegui ": null,
"qterminal ": null,
"quadrapassel ": null,
"quagga ": null,
"quake ": null,
"quassel ": null,
"quod libet ": null,
"qutebrowser ": null,
"redis ": null,
"remmina ": null,
"retroarch ": null,
"libretro ": null,
"rox ": null,
"rpcs3 ": null,
"scrcpy ": null,
"scummvm ": null,
"seahorse ": null,
"seamonkey ": null,
"short circuit ": null,
"shotcut ": null,
"shotwell ": null,
"simplescreenrecorder ": null,
"simple-scan ": null,
"skanlite ": null,
"skrooge ": null,
"skype ": null,
"slack ": null,
"smb4k ": null,
"smplayer ": null,
"smtube ": null,
"snes9x ": null,
"soundconverter ": null,
"soundkonverter ": null,
"sparkleshare ": null,
"sparky ": null,
"speak ": null,
"spectacle ": null,
"spectator ": null,
"speed test ": null,
"spotify ": null,
"ssh ": null,
"steam ": null,
"stellarium ": null,
"strawberry ": null,
"stremio ": null,
"stunt rally ": null,
"subdownloader ": null,
"sublime text ": null,
"subtitleeditor ": null,
"sudoku ": null,
"sugarizer ": null,
"sugar chess ": null,
"supertuxkart ": null,
"supertux ": null,
"sweeper ": null,
"sweep ": null,
"sweet home 3d ": null,
"switchboard ": null,
"synfig studio ": null,
"systemsettings ": null,
"system-config-printer ": null,
"system-tool ": null,
"teamspeak ": null,
"teams for linux ": null,
"teamtime ": null,
"teatime ": null,
"teeworlds ": null,
"telegram ": null,
"tetris ": null,
"texmaker ": null,
"texstudio ": null,
"texworks ": null,
"thunar ": null,
"thunderbird ": null,
"tic tac toe ": null,
"tigervnc ": null,
"torbrowser": null,
"torcs ": null,
"torrent ": null,
"tor ": null,
"transmission ": null,
"tundra ": null,
"tutanota ": null,
"tuxcmd ": null,
"tuxguitar ": null,
"tuxpuck ": null,
"tux futebol ": null,
"tux paint ": null,
"tux typing ": null,
"tux, of math ": null,
"tvtime ": null,
"twistypuzzle ": null,
"twist": null,
"twitter ": null,
"typora ": null,
"ufw ": null,
"uget ": null,
"uhttpd ": null,
"ultimate media downloader 2 ": null,
"urban terror ": null,
"urdig ": null,
"uritool ": null,
"url image preview plugin ": null,
"v4l2onvif ": null,
"v4l2tools ": null,
"v4l2web ": null,
"v4l2-rtspserver ": null,
"v4l-utils ": null,
"valgrind ": null,
"viber ": null,
"vidcutter ": null,
"video downloader ": null,
"vim ": null,
"vivaldi ": null,
"vlc ": null,
"vscode ": null,
"vscodium ": null,
"vuepilot ": null,
"vuescan ": null,
"vue ": null,
"vídeos ": null,
"wallpapers ": null,
"wallpaper downloader ": null,
"webrtc-streamer ": null,
"webstorm ": null,
"webtorrent ": null,
"weechat ": null,
"whatami ": null,
"whatsappqt ": null,
"whatsapp-for-linux ": null,
"whatsdesk ": null,
"what ip ": null,
"what-snap ": null,
"whipper ": null,
"whitesur ": null,
"winbox ": null,
"wine": null,
"wireguard ": null,
"wireless ": null,
"wireshark ": null,
"wordpress ": null,
"wps office ": null,
"x11vnc ": null,
"xboard ": null,
"xlsx ": null,
"xnconvert ": null,
"xnoise ": null,
"xnsketch ": null,
"xnview": null,
"xonotic ": null,
"xpad ": null,
"xpdf ": null,
"xreader ": null,
"xscreensaver ": null,
"xsensors ": null,
"x-moto ": null,
"yad ": null,
"yakuake ": null,
"yandex-weather-cli ": null,
"yaru gtk theme ": null,
"yaru-colors ": null,
"youdaonote--easy ": null,
"youp for whatsapp ": null,
"youtube music desktop ": null,
"youtube-dl ": null,
"yuzu ": null,
"zenmap ": null,
"zim ": null,
"zint-qt ": null,
"zoom ": null,
"zsnes ": null,
},
onAutocomplete: function() {
        $("#formsearch").submit();
   },
      limit: 5
  });
});
